# Generated by Django 4.2.19 on 2025-02-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0003_epubtext_text_chunks_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='epubtext',
            name='last_read_chunk',
            field=models.IntegerField(default=0),
        ),
    ]
